### ISSUE TITLE
Maven?

### ISSUE THREAD

**Issue by LousyLynx** [djxy/PermissionManager-2.0#11]
Hello! I am trying to make a chat plugin using PermissionManager, but as of now, it is kind of hard. I was thinking that you could make a TravisCI, that is hooked up to a Bintray so that people can easily add your code as a dependency? That would really help me. If you want, I can try and help you 😄

**Comment by djxy** [comment]
I will check that. Currently you can use the jar, but it could be a good idea to have something like that.

**Comment by djxy** [comment]
Do you need help with your project?

**Comment by LousyLynx** [comment]
??
