### ISSUE TITLE
Feature request /pm load groups

### ISSUE THREAD

**Issue by ProsperCraft** [djxy/PermissionManager-2.0#12]
When doing a lot of edits via the files it would be helpful if we could load all of the groups from the server.  Right now you can save all groups to file but not load them all, unless I am missing something.

**Comment by djxy** [comment]
Yes, currently there is no command for this. I could add it.

**Comment by djxy** [comment]
Your commands https://github.com/djxy/PermissionManager-2.0/releases/tag/v2.4.0
