### ISSUE TITLE
Feature request - Ability to jump in the menu to a specific user.

### ISSUE THREAD

**Issue by ProsperCraft** [djxy/PermissionManager-2.0#13]
Right now we have 16 pages of users which will grow quickly and finding the specific user you want in that list can take some time, perhaps you could add a command like
/pm #user that would jump the menu to editing that user?

**Comment by djxy** [comment]
Yes, I can add this. I will add two commands. `/pm groups #group` and `/pm users #users`

**Comment by ProsperCraft** [comment]
Thank you! I really love your menu system for editing permissions, it will make it much easier for my staff, keep up the great work!

**Comment by djxy** [comment]
Your commands https://github.com/djxy/PermissionManager-2.0/releases/tag/v2.4.0
