### ISSUE TITLE
Command help system

### ISSUE THREAD

**Issue by djxy** [djxy/PermissionManager-2.0#16]
A command help should be returned to the player when he send a bad command or when the last char is ?.

**Comment by hugeblank** [comment]
Suggestion: when you open the UI, across from each option could be a clickable light green '?' Where you can get help for each individual option. 

I.E. the front page has:
Groups
Users
Debug
And 1 other thing that I can't remember of the top of my head

So you could have the '?' Be on the left:
? Groups
? Users
? Debug
Or on the opposite edge of chat:
Groups *a bunch of spaces* ?
Users  *a bunch of spaces* ?
Debug  *a bunch of spaces* ?

**Comment by djxy** [comment]
What would you like for the help message? I would like to gave an example of message.

**Comment by hugeblank** [comment]
Well let's say you needed help on what 'groups' does in the menu when you first type in '/pm menu'. You would click on the question mark, and something like this would show up:

Groups:
To set up permissions, options, or promotions for a select amount of players that you can control, this would be what you would want to click. Groups are used when you want to provide a list of permissions to a specific crowd of people. 

I'd say make it look good with a box, similar to how the UI is.
