### ISSUE TITLE
How to deny build permissions in specific world

### ISSUE THREAD

**Issue by AnZaNaMa** [djxy/PermissionManager-2.0#19]
I understand how I can deny permissions and how to do world-specific stuff, I'm just trying to figure out if there's a permission for building/breaking blocks or is it an option or how does that work?

**Comment by djxy** [comment]
It depends the plugins you are using, but it should ve an option.

**Comment by AnZaNaMa** [comment]
so there is no default vanilla permission or sponge permission?
do you know of any that have a node for it?

**Comment by djxy** [comment]
You could use the debug mode to check the permissions tested when you break/place a block.

**Comment by AnZaNaMa** [comment]
oh cool, thanks!
