### ISSUE TITLE
Permissions not working on plugin SkinsRestorer

### ISSUE THREAD

**Issue by BabelSolea** [djxy/PermissionManager-2.0#22]
plugin SkinsRestorer have permissions:
skinsrestorer.playercmds
skinsrestorer.cmds
skinsrestorer.bypasscooldown

i tried deny permissions on default group:
/pm groups default deny permission skinsrestorer.playercmds
/pm groups default deny permission skinsrestorer.cmds
/pm groups default deny permission skinsrestorer.bypasscooldown

/pm groups default deny permission skinsrestorer.*

then save group but that not working, players in default group still can using commands from that plugin.

did i some wrong or that is error?

**Comment by djxy** [comment]
Can I have the file of your group with the file of à player that is in the group?

**Comment by BabelSolea** [comment]
default.yml

permissions:
- -skinsrestorer.cmds
- -skinsrestorer.bypasscooldown
- -skinsrestorer.playercmds
- -skinrestorer.*
rank: 10
default: true

Owner.yml

permissions:
- '*'
options:
    prefix: '[Owner]'
    'prefix:': '[Owner]'

Users: that really hard to searching.... http://image.prntscr.com/image/d14de00d804f44c287b9e0c67a439454.png

any user.yml

groups:
- default
options:
    language: eng

owner.yml

permissions:
- '*'
groups:
- Owner
options:
    language: eng

**Comment by djxy** [comment]
default.yml is in the folder `groups`?

**Comment by BabelSolea** [comment]
yeah! all configurations is default.

**Comment by djxy** [comment]
Can you use pastebin please? It will be better to understand your config.

**Comment by BabelSolea** [comment]
link to zip of my
server/config/permissionmanager

https://drive.google.com/open?id=0BxEbenzEP7nQTHp0LWd0Tm5pRnc

**Comment by djxy** [comment]
Okay thank you. I will test that later. Can you give the link to download skinsrestorer?

**Comment by BabelSolea** [comment]
https://www.spigotmc.org/resources/skinsrestorer.2124/

**Comment by djxy** [comment]
Are you using Pore?

**Comment by BabelSolea** [comment]
Sponge? )
i using sponge vanilla #171 BETA. (for 1.11)

**Comment by djxy** [comment]
Yes, but you can't use Bukkit plugins or Spigot with Sponge.

**Comment by BabelSolea** [comment]
SkinsRestorer allow Sponge

**Servers:**
Spigot
CraftBukkit
PaperSpigot
Sponge

**Clouds:**
BungeeCord
Waterfall
FlexPipe

**Comment by BabelSolea** [comment]
that plugin working fine, but i cant manage permissions.

**Comment by djxy** [comment]
Okay I don't know that. I will test that when I will comeback home.

**Comment by djxy** [comment]
Cab you use the commands without the permissions?

**Comment by BabelSolea** [comment]
i can use command with and without permissions

**Comment by BabelSolea** [comment]
command of that plugin

**Comment by djxy** [comment]
I think this is à bug from Skinsrestorer. The author didn't set the permissions for the commands on the Sponge version.

**Comment by djxy** [comment]
You should ask hin to fix it.

**Comment by BabelSolea** [comment]
ok thanks for help me) i do that

**Comment by BabelSolea** [comment]
yeah, one support of there plugin did join into my server and check/test it
they will work about it
