### ISSUE TITLE
Prefixes no work

### ISSUE THREAD

**Issue by Bizeran** [djxy/PermissionManager-2.0#23]
I am using sponge version of this plugin. The plugin says the prefixes are there but they do not display in chat. I have checked the configs. I have deleted all other plugins that could interfere. Please get back to me on my email via epicface2700:gmail.com

**Comment by djxy** [comment]
Do you have a plugin that handle the prefixes? PermissionManager can't format the chat. Nucleus can display the prefixes in the chat.

**Comment by Bizeran** [comment]
thank you i will add nucleaus today. So permissionmanager wont display the
prefixes?

**Comment by djxy** [comment]
You set the prefixes with PermissionManager and you use Nucleus to display them.
