### ISSUE TITLE
Per-world config disappearing

### ISSUE THREAD

**Issue by hugeblank** [djxy/PermissionManager-2.0#24]
I have a group called "Member" that I want as a default. The player spawns in a hub and can go to survival or creative. I want it to have a bunch of plotsquared permissions on the creative world, and a bunch of griefprevention perms in the survival world. Along with this I had a few global perms, for the chat. I had all the configs set up, so I started the server. After the server started, it created a new default config (seperate from "Member"), which alone was annoying. But, when I went to go and switch default back to "Member", it deleted all of the configs that I had arranged for it, leaving me a little frustrated, as I forgot to back the configs up.

I was using permissionmanager 2.5.1

**Comment by hugeblank** [comment]
OH XD you fixed it

**Comment by hugeblank** [comment]
sike. Just updated, and it's still an issue in 2.5.2

**Comment by djxy** [comment]
When you edited your file, did you test it before on a validator online? If not, it may be the problem. May be you did an error and when the server loaded, the file didn't loaded because the error.

**Comment by hugeblank** [comment]
@djxy No I didn't... Where could I find one?
