### ISSUE TITLE
English Wiki Page "How to Start" doesn't tell you how to start

### ISSUE THREAD

**Issue by majix560** [djxy/PermissionManager-2.0#25]
[English Wiki Page "How to Start"](https://github.com/djxy/PermissionManager-2.0/wiki/Eng-%E2%80%94-How-to-start) doesn't tell you how to start.
It gives some basic information, but the stuff it tells you has **_*nothing*_** to do with actually using this plugin, let alone how to get started with it.

**Comment by djxy** [comment]
Yes, I give some basics informations, these can guide anyone, but I can't know in advance what you want to do. You can check the commands or use the menu if you are not sure how to edit the files.

**Comment by majix560** [comment]
In order to be able to rightfully call it "How to start" you have tell people at least the "basics" of how to use the plugin.
Not just the basic concepts.
After-all, you can't tell people "how to start" using something if you don't actually tell them how to start using it.

**Comment by djxy** [comment]
I don't see what you want more. I tell you how to give you all the rights like an OP, I give you à tool to validate your files, I say that if you don't want to edit your file you can use the commands or the menu and then I explain the difference between the default group and the default subject.

Then I can't say you which commands to use, I don't know what you want to do. Thats why How to start gives somes tricks to make sure you have a better idea of the basics.
