### ISSUE TITLE
Not parsing spaces

### ISSUE THREAD

**Issue by skulltraill** [djxy/PermissionManager-2.0#3]
Hi

When I am trying to set a prefix, if I use a space:

`/pm groups admin set option prefix '&6[Top Brass]&f'`

it says:

`The value 'world' isn't valid.`

Please allow us to use spaces when we surround the words with quotation marks.

Thanks.

**Comment by djxy** [comment]
Hi,
thanks for the report. You know, currently you can edit the file of the group Admin and then load it.

**Comment by skulltraill** [comment]
Thank you for the fast reply. 

Yes I know about manually editing, but would be nice to have it in the in-game menu also...

It's not urgent... so take your time.. but it would be nice to have :)

**Comment by djxy** [comment]
This is fixed. 

https://github.com/djxy/PermissionManager-2.0/releases/tag/v2.0.1
