### ISSUE TITLE
some translation confuse

### ISSUE THREAD

**Issue by subtank** [djxy/PermissionManager-2.0#31]
i want translation this plugin,but here are some confuse:
"Do you really want to delete all the groups of the group {group} globally?
did it mean delete all sub-groups in group A?

**Comment by subtank** [comment]
or it is a same code to delete a group?

**Comment by djxy** [comment]
Wait before translating this version. I'm currently working on the new version (3.0.0) and There Will be some changes. 

You would like to translate it in?

**Comment by djxy** [comment]
But, this translation means: Do you want to delete all the global groups of X?

**Comment by subtank** [comment]
Ok，thx.i will stop translation till 3.0 come out

**Comment by subtank** [comment]
i can't open pm menu in game, how can i open it?

**Comment by djxy** [comment]
You need the permission and you have to do /pm menu

**Comment by subtank** [comment]
thanks
