### ISSUE TITLE
Installation Problems:

### ISSUE THREAD

**Issue by Kiriakashi** [djxy/PermissionManager-2.0#32]
I recently tried using this for ranks in my server, and when I started the server up it didn't do anything.

I typed:
/pw
Nothing.

I typed:
/pw menu
Nothing.

Went to console and typed:
pm users Kiriakashi set permission *

Nothing?

**Comment by Kiriakashi** [comment]
19.01 06:27:55 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'pm users Kiriakashi set permission *' for source DedicatedServer: io/github/djxy/permissionmanager/subjects/user/User
19.01 06:27:55 [Server] INFO java.lang.NoClassDefFoundError: io/github/djxy/permissionmanager/subjects/user/User
19.01 06:27:55 [Server] INFO at io.github.djxy.permissionmanager.subjects.user.UserCollection.createUser(UserCollection.java:108) ~[UserCollection.class:?]
19.01 06:27:55 [Server] INFO at io.github.djxy.permissionmanager.subjects.user.UserCollection.createUser(UserCollection.java:38) ~[UserCollection.class:?]
19.01 06:27:55 [Server] INFO at io.github.djxy.permissionmanager.subjects.user.UserCollection.get(UserCollection.java:57) ~[UserCollection.class:?]
19.01 06:27:55 [Server] INFO at io.github.djxy.permissionmanager.commands.parsers.UserParser.parse(UserParser.java:23) ~[UserParser.class:?]
19.01 06:27:55 [Server] INFO at io.github.djxy.permissionmanager.commands.parsers.UserParser.parse(UserParser.java:17) ~[UserParser.class:?]
19.01 06:27:55 [Server] INFO at io.github.djxy.customcommands.Node.getValues(Node.java:98) ~[Node.class:?]
19.01 06:27:55 [Server] INFO at io.github.djxy.customcommands.CustomCommands$CommandCallable.process(CustomCommands.java:143) ~[CustomCommands$CommandCallable.class:?]
19.01 06:27:55 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2202-5.1.0-BETA-2039]
19.01 06:27:55 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:295) [SpongeCommandManager.class:1.10.2-2202-5.1.0-BETA-2039]
19.01 06:27:55 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
19.01 06:27:55 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
19.01 06:27:55 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
19.01 06:27:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
19.01 06:27:55 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
19.01 06:27:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
19.01 06:27:55 [Server] INFO Caused by: java.lang.ClassNotFoundException: io.github.djxy.permissionmanager.subjects.user.User
19.01 06:27:55 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO ... 15 more
19.01 06:27:55 [Server] INFO Caused by: java.lang.NoClassDefFoundError: io/github/djxy/permissionmanager/subjects/Subject
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO ... 15 more
19.01 06:27:55 [Server] INFO Caused by: java.lang.ClassNotFoundException: io.github.djxy.permissionmanager.subjects.Subject
19.01 06:27:55 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
19.01 06:27:55 [Server] INFO ... 15 more

**Comment by djxy** [comment]
Which version of Sponge and of PermissionManager Do you have?

**Comment by Kiriakashi** [comment]
Hi! @djxy I got it fixed. One question, how do I add prefixes to ranks? Or, could you add that in a future update

**Comment by djxy** [comment]
You have to set the option prefix and then use a plugin to format your chat. Nucleus can format to your chat.

For questions like this, you should ask them on the Discord channel.
