### ISSUE TITLE
[Feature Request] Permission Inheritance

### ISSUE THREAD

**Issue by Siriuo** [djxy/PermissionManager-2.0#33]
Firstly a bit of feedback. So far this has been very stable and simple to use.

One feature I would like to see is permission inheritance.
For example:

If there are 4 groups [members, donator, moderator, admin] setting a single line in the moderatorin the yml file called inheritance: 'donator' or similar would give the moderator rank all permissions from the donator group and the member group (if donator group has inheritence: 'member').

**Comment by djxy** [comment]
You can, you have to add a group to another one. So, if you add the group donator to Moderator. Moderator will inherit every permissions and options donator has.

**Comment by Siriuo** [comment]
Cool looks like that works.

Thanks :)
