### ISSUE TITLE
Error's when trying to do anything

### ISSUE THREAD

**Issue by sonic1238** [djxy/PermissionManager-2.0#5]
i put the plugin on my server but now, even OP's cant do anything since it classifies then as default, i cant even access the /pm menu because no matter how i go about it it wont let me get that permission to even do it. please help

if you need to chat here is my discord

https://discord.gg/8kGCChP - Name is VanillaKilla

**Comment by djxy** [comment]
In the console, do this. /pm users your_name set permission *

**Comment by sonic1238** [comment]
thank you so much! it worked

but i have one question now, when adding a permission to a group, 

/pm groups Default set permission <PERMISSION> - does <PERMISSION> have to be the node(nucleus.home.set.base) or just the / and the command (ex. /homeset)
