### ISSUE TITLE
Some things needs to rework, don't it?

### ISSUE THREAD

**Issue by Exchy** [djxy/PermissionManager-2.0#7]
I don't receive any response in console when I type pm, pm menu; literally nothing to appear. Just once It allowed me to watch the "possibilities" but after that I couldn't ever reproduce that window again, is it scanning plugins for perms or what?
And yeah, maybe u know such plugin called "nucleus", so is it "manager" or "nucleus" not allowing OP to change even the GAMEMODE (carl!) without "*"? waiting for answer 👍 
![capture](https://cloud.githubusercontent.com/assets/22306747/18650340/4abb0750-7ecd-11e6-96ad-0503008fbad2.PNG) :D
P.S. Can I just somehow look at users "properties" for example his groups, perms, etc?

**Comment by djxy** [comment]
You can't change then language of the console. You can only change your language in game. You should do this `/pm users your_username set permission *`, you will be able to do all the commands.

**Comment by Exchy** [comment]
And since when /op command became useless, that's weird, don't u think so? (The image was just a joke, about "changing language in console"). So what about console ignoring when writing pm, pm menu? Cuz without any console-UI it's hard to find what exactly commands u should write to give myself perms, since in-game I don't have permission to /pm (oh, the irony is rich).  I'm referring/relating your program to PEX.
![capture](https://cloud.githubusercontent.com/assets/22306747/18650664/f30fceb2-7ece-11e6-82c4-996ccd15c6ce.PNG)
Maybe I'm just stupid and I have some problems with understanding

**Comment by djxy** [comment]
The console has a ll the permission, so you can do any commands. Also, you can't use the menu in the console, because you need to interact with it.

When you install a permission plugin, the OP system doesn't work anymore.

**Comment by Exchy** [comment]
>so you can do any commands
Nice, but what commands, the program must show you, how can you add permissions
> you can't use the menu in the console
AND, in-game is denied also, due to not being able to properly "*" yourself in console, cuz as a new noob - you just don't know HOW, you must go to the internet and find special page with all "PM" commands (https://github.com/djxy/PermissionManager-2.0/wiki/Eng-%E2%80%94-Commands). I mean it just need to be shown in console if you can't use "help" there. Just tell me you understand please :3

**Comment by djxy** [comment]
The commands are on the wiki/forum of each plugin, you have to find them. 

I'm not sure to understand what you want.

**Comment by Exchy** [comment]
Ok, it try another way. I just downloaded your PM. I see that "op" is not working, I want to have all perms. I'm going to console and what's then? Long searching for your plugin commands in web? No, everyone  wants to see this.
![capture](https://cloud.githubusercontent.com/assets/22306747/18651184/6c080caa-7ed2-11e6-8c3e-f0d764568f48.PNG)
All commands of "Permission Manager" with explanation In one place. Knowing what to write without surfing Google. That what I tried to say

**Comment by djxy** [comment]
You have everything here https://github.com/djxy/PermissionManager-2.0/wiki

To have all the permissions, you have to do this `/pm users your_username set permission *`

**Comment by Exchy** [comment]
I give up, close the thread, thx

**Comment by djxy** [comment]
Okay, but I don't understand what the problem. You wanted à link with all the commands, I gave you the wiki and you wanted to know the command to have all the permission. I will close the thread.
