### ISSUE TITLE
Can't use CommandBlock

### ISSUE THREAD

**Issue by lujiren** [djxy/PermissionManager-2.0#8]
spongeforge1.10.2-2092-5.0.0-BETA-1746
permissionManager-2.1.3-API-5.X

Just CAN'T place or modify Command Block.
When permissionManager is removed, everything works again.

in DEBUG mode, When I try to place Command Block 
Console print [09:29:43] [Server thread/INFO] [io.github.djxy.permissionmanager.subjects.group.Group/]: admin get permission value for  - []

**Comment by djxy** [comment]
You have to add the permission `/pm groups admin set permission *` to the admin group and then add yourself to the admin group `/pm users your_username add group admin`.

**Comment by lujiren** [comment]
I have done that before, still not work. 
@djxy

**Comment by djxy** [comment]
Okay, I will check that tomorrow.

**Comment by lujiren** [comment]
Thx! ❤️

**Comment by djxy** [comment]
Is it working, I haven't had the time to test.

**Comment by lujiren** [comment]
Still can't place CB in PermissionManager-2.1.4-API-5.X @djxy
