### ISSUE TITLE
worldedit commands keep reappearing.

### ISSUE THREAD

**Issue by jelaw21** [djxy/PermissionManager-2.0#9]
I have a "player" group and an "admin" group. My "player" group is the default group. First off, no matter how many times I delete it, the generic default group keeps re-appearing. Also, not matter how many times I delete them, all the world edit commands keep showing up in my player group and the generic default.

**Comment by djxy** [comment]
Some plugins give permissions to the default group. I will try something to avoid that.

**Comment by djxy** [comment]
Which version are you using. Worldedit and PermissionManager.

**Comment by jelaw21** [comment]
PM: 2.1.3  Worldedit: 6.1.4

**Comment by djxy** [comment]
I fixed it, I will upload the update today.

**Comment by jelaw21** [comment]
Sweet.

**Comment by djxy** [comment]
2.1.4 should fix your problem.

**Comment by jelaw21** [comment]
Except notw when I login for the first time it gives me a null pointer
exception: group

**Comment by djxy** [comment]
I want the logs. I will fix it.

**Comment by jelaw21** [comment]
Where would I find those since no crash report just kicked me out of server.

**Comment by djxy** [comment]
If it return a null pointer exception, you should have a crash report on your logs.
